name: main

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3

            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build

            - name: Deploy
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  aws s3 sync \
                    build s3://jaejun.me --delete \
                    --region ap-northeast-2

            - name: Invalidation
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  aws cloudfront create-invalidation \
                    --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} \
                    --paths "/*" \
                    --region ap-northeast-2
